name: Build

on:
  push:
    branches:
      - forcing_9
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_and_apk:
    name: "Local tests and APKs"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      security-events: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

#      - name: Check build-logic
#        run: ./gradlew :build-logic:convention:check

        #run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

 #     - name: Check Dependency Guard
 #      id: dependencyguard_verify
 #       continue-on-error: true
 #       run: ./gradlew dependencyGuard

      # Run local tests after screenshot tests to avoookoid wrong UP-TO-DATE. TODO: Ignore screenshots.
 #     - name: Run local tests
 #       run: ./gradlew testDemoDebug :lint:test

      - name: Build all build type and flavor permutations
        run: ./gradlew clean assembleDebug
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_TOKEN }}           

 #     - name: Check lint
 #       run: ./gradlew :app:lintProdRelease :app-nia-catalog:lintRelease :lint:lint

 #     - name: Check badging
 #       run: ./gradlew :app:checkProdReleaseBadging

      - name: Gradle cache user home
        uses: actions/upload-artifact@v4
        with:
          name: zulu-sl
          path: |
             /home/runner/.gradle/caches

