name: Build

on:
  push:
    branches:
      - test_veri
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_and_apk:
    name: "Local tests and APKs"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      security-events: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}     

      - name: Check build-logic
        run: ./gradlew clean assembleDebug
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_TOKEN }}

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: zulu
          path: |
             /home/runner/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/okhttp/4.12.0/2f4525d4a200e97e1b87449c2cd9bd2e25b7e8cd/
            

      