name: Build

on:
  push:
    branches:
      - forcing_11
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_and_apk:
    name: "Local tests and APKs"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      security-events: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17


      - name: Build Debug
        run: ./gradlew clean :core:network:compileDemoDebugJavaWithJavac
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_TOKEN }}            

      - name: Gradle cache user home
        uses: actions/upload-artifact@v4
        with:
          name: zulu-sl
          path: |
             /home/runner/.gradle/caches

